/**
 * 梅花易数核心算法
 * Plum Blossom Numerology Core Algorithm
 * 
 * 实现梅花易数的各种起卦方法、体用关系分析、互卦变卦计算、
 * 五行生克分析和综合断卦算法。
 * 
 * Implements various divination methods, body-use relationship analysis,
 * mutual and changed hexagram calculations, five-element analysis,
 * and comprehensive interpretation algorithms.
 */

import type {
  WuXingElement,
  WuXingElementEN,
  BaGua,
  BaGuaEN,
} from './wuxingData';
import {
  BAGUA_WUXING_MAP,
  BAGUA_WUXING_MAP_EN,
  BAGUA_NUMBER_MAP,
  getSeasonByMonth,
  getElementSeasonalState,
  getElementSeasonalStateEN,
  getBaGuaByNumber,
  getBaGuaByNumberEN,
  getBaGuaElement,
  getBaGuaElementEN,
  WUXING_RELATION_MATRIX,
} from './wuxingData';

// ==================== 类型定义 Type Definitions ====================

/**
 * 爻线类型
 * Line type (Yin or Yang)
 */
export type YaoLine = '阳' | '阴';
export type YaoLineEN = 'Yang' | 'Yin';

/**
 * 单爻数据
 * Single line data
 */
export interface Yao {
  line: YaoLine;
  lineEN: YaoLineEN;
  number: number;        // 该爻对应的数字（用于计算）
  isMoving: boolean;     // 是否为动爻
  position: number;      // 爻的位置（1-6，从下往上）
}

/**
 * 卦象数据
 * Hexagram data
 */
export interface GuaXiang {
  name: string;          // 卦名
  nameEN: string;        // Hexagram name (English)
  upperTrigram: BaGua;   // 上卦
  upperTrigramEN: BaGuaEN;
  lowerTrigram: BaGua;   // 下卦
  lowerTrigramEN: BaGuaEN;
  lines: Yao[];          // 六爻
  element: WuXingElement;      // 卦的五行属性
  elementEN: WuXingElementEN;
  number: number;        // 卦的序号
  binary: string;        // 二进制表示（从下到上）
}

/**
 * 起卦方法类型
 * Divination method types
 */
export type DivinationMethod = '时间起卦' | '数字起卦' | '文字起卦' | '随机起卦';
export type DivinationMethodEN = 'Time' | 'Number' | 'Text' | 'Random';

/**
 * 起卦结果
 * Divination result
 */
export interface DivinationResult {
  method: DivinationMethod;
  methodEN: DivinationMethodEN;
  timestamp: Date;
  input: any;            // 起卦输入（时间、数字、文字等）
  mainGua: GuaXiang;     // 主卦
  mutualGua?: GuaXiang;  // 互卦
  changedGua?: GuaXiang; // 变卦
  movingLine: number;    // 动爻位置（1-6）
  bodyGua: GuaXiang;     // 体卦
  useGua: GuaXiang;      // 用卦
  bodyTrigram: BaGua;    // 体卦的经卦
  useTrigram: BaGua;     // 用卦的经卦
}

/**
 * 五行关系分析结果
 * Five-element relationship analysis result
 */
export interface WuXingAnalysis {
  bodyElement: WuXingElement;
  bodyElementEN: WuXingElementEN;
  useElement: WuXingElement;
  useElementEN: WuXingElementEN;
  relation: '生' | '克' | '被生' | '被克' | '同';
  relationEN: 'generates' | 'destroys' | 'generated by' | 'destroyed by' | 'same';
  bodySeasonalState: '旺' | '相' | '休' | '囚' | '死';
  bodySeasonalStateEN: 'Prosperous' | 'Generating' | 'Resting' | 'Imprisoned' | 'Dead';
  useSeasonalState: '旺' | '相' | '休' | '囚' | '死';
  useSeasonalStateEN: 'Prosperous' | 'Generating' | 'Resting' | 'Imprisoned' | 'Dead';
  interpretation: string;
  interpretationEN: string;
}

/**
 * 综合断卦结果
 * Comprehensive interpretation result
 */
export interface ComprehensiveInterpretation {
  divinationResult: DivinationResult;
  wuxingAnalysis: WuXingAnalysis;
  overallInterpretation: string;
  overallInterpretationEN: string;
  advice: string;
  adviceEN: string;
  confidence: number;    // 置信度（0-100）
  aspects: {
    career?: string;
    careerEN?: string;
    love?: string;
    loveEN?: string;
    wealth?: string;
    wealthEN?: string;
    health?: string;
    healthEN?: string;
  };
}

// ==================== 基础工具函数 Basic Utility Functions ====================

/**
 * 生成随机数（用于随机起卦）
 * Generate random number (for random divination)
 * @param min 最小值
 * @param max 最大值
 * @returns 随机整数
 */
export function generateRandomNumber(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * 计算数字除以8的余数（先天八卦数）
 * Calculate number mod 8 (Earlier Heaven bagua number)
 * @param number 输入数字
 * @returns 1-8的数字（0视为8）
 */
export function calculateMod8(number: number): number {
  const remainder = number % 8;
  return remainder === 0 ? 8 : remainder;
}

/**
 * 计算数字除以6的余数（用于动爻）
 * Calculate number mod 6 (for moving line)
 * @param number 输入数字
 * @returns 1-6的数字（0视为6）
 */
export function calculateMod6(number: number): number {
  const remainder = number % 6;
  return remainder === 0 ? 6 : remainder;
}

/**
 * 根据数字生成爻
 * Generate Yao line based on number
 * @param number 输入数字
 * @param isMoving 是否为动爻
 * @param position 爻的位置
 * @returns Yao对象
 */
export function generateYao(number: number, isMoving: boolean, position: number): Yao {
  // 奇数为阳爻，偶数为阴爻
  const isYang = number % 2 !== 0;
  return {
    line: isYang ? '阳' : '阴',
    lineEN: isYang ? 'Yang' : 'Yin',
    number,
    isMoving,
    position,
  };
}

/**
 * 根据数字生成三爻卦（经卦）
 * Generate trigram based on number
 * @param number 1-8的数字
 * @returns 三爻数组
 */
export function generateTrigramLines(number: number): [YaoLine, YaoLine, YaoLine] {
  // 先天八卦二进制表示（从下到上）
  const trigramBinary: Record<number, [YaoLine, YaoLine, YaoLine]> = {
    1: ['阳', '阳', '阳'],  // 乾 ☰
    2: ['阳', '阳', '阴'],  // 兑 ☱
    3: ['阳', '阴', '阳'],  // 离 ☲
    4: ['阳', '阴', '阴'],  // 震 ☳
    5: ['阴', '阳', '阳'],  // 巽 ☴
    6: ['阴', '阳', '阴'],  // 坎 ☵
    7: ['阴', '阴', '阳'],  // 艮 ☶
    8: ['阴', '阴', '阴'],  // 坤 ☷
  };
  
  const normalizedNumber = calculateMod8(number);
  return trigramBinary[normalizedNumber];
}

/**
 * 生成六爻卦
 * Generate hexagram lines
 * @param upperNumber 上卦数字
 * @param lowerNumber 下卦数字
 * @param movingLine 动爻位置（1-6）
 * @returns 六爻数组
 */
export function generateHexagramLines(
  upperNumber: number,
  lowerNumber: number,
  movingLine: number
): Yao[] {
  const lines: Yao[] = [];
  
  // 生成下卦三爻（1-3爻）
  const lowerTrigramLines = generateTrigramLines(lowerNumber);
  for (let i = 0; i < 3; i++) {
    lines.push({
      line: lowerTrigramLines[i],
      lineEN: lowerTrigramLines[i] === '阳' ? 'Yang' : 'Yin',
      number: lowerNumber,
      isMoving: i + 1 === movingLine,
      position: i + 1,
    });
  }
  
  // 生成上卦三爻（4-6爻）
  const upperTrigramLines = generateTrigramLines(upperNumber);
  for (let i = 0; i < 3; i++) {
    lines.push({
      line: upperTrigramLines[i],
      lineEN: upperTrigramLines[i] === '阳' ? 'Yang' : 'Yin',
      number: upperNumber,
      isMoving: i + 4 === movingLine,
      position: i + 4,
    });
  }
  
  return lines;
}

/**
 * 生成卦象对象
 * Generate hexagram object
 * @param upperNumber 上卦数字
 * @param lowerNumber 下卦数字
 * @param movingLine 动爻位置
 * @returns GuaXiang对象
 */
export function generateGuaXiang(
  upperNumber: number,
  lowerNumber: number,
  movingLine: number
): GuaXiang {
  const upperTrigram = getBaGuaByNumber(upperNumber);
  const lowerTrigram = getBaGuaByNumber(lowerNumber);
  const upperTrigramEN = getBaGuaByNumberEN(upperNumber);
  const lowerTrigramEN = getBaGuaByNumberEN(lowerNumber);
  
  const lines = generateHexagramLines(upperNumber, lowerNumber, movingLine);
  
  // 卦的五行属性取下卦（体卦）的五行
  const element = getBaGuaElement(lowerTrigram);
  const elementEN = getBaGuaElementEN(lowerTrigramEN);
  
  // 生成二进制表示（从下到上）
  const binary = lines.map(l => l.line === '阳' ? '1' : '0').join('');
  
  // 简化的卦名生成（实际应用中可能需要完整的64卦名称表）
  const name = `${upperTrigram}上${lowerTrigram}下`;
  const nameEN = `${upperTrigramEN} over ${lowerTrigramEN}`;
  
  return {
    name,
    nameEN,
    upperTrigram,
    upperTrigramEN,
    lowerTrigram,
    lowerTrigramEN,
    lines,
    element,
    elementEN,
    number: upperNumber * 10 + lowerNumber, // 简化的卦序
    binary,
  };
}

// ==================== 起卦方法 Divination Methods ====================

/**
 * 农历年份数字映射（地支序号）
 * Lunar year number mapping (Earthly Branch index)
 * 梅花易数中，年的数字取地支序号：子=1, 丑=2, ..., 亥=12
 * In Plum Blossom, year number uses Earthly Branch: Zi=1, Chou=2, ..., Hai=12
 */
export function getYearBranchNumber(year: number): number {
  // 地支序号：子(1), 丑(2), 寅(3), 卯(4), 辰(5), 巳(6),
  //           午(7), 未(8), 申(9), 酉(10), 戌(11), 亥(12)
  // 公历年转地支：(year - 4) % 12 + 1
  return ((year - 4) % 12) + 1;
}

/**
 * 时间起卦法
 * Time-based divination method
 *
 * 算法说明 / Algorithm description:
 * 上卦 G_u = (年支数 + 月数 + 日数) mod 8
 * 下卦 G_l = (年支数 + 月数 + 日数 + 时支数) mod 8
 * 动爻 M = (年支数 + 月数 + 日数 + 时支数) mod 6
 *
 * Upper trigram: G_u = (YearBranch + Month + Day) mod 8
 * Lower trigram: G_l = (YearBranch + Month + Day + HourBranch) mod 6
 * Moving line:   M   = (YearBranch + Month + Day + HourBranch) mod 6
 *
 * 时辰与地支对应：
 * 子时(23-01)=1, 丑时(01-03)=2, 寅时(03-05)=3, 卯时(05-07)=4,
 * 辰时(07-09)=5, 巳时(09-11)=6, 午时(11-13)=7, 未时(13-15)=8,
 * 申时(15-17)=9, 酉时(17-19)=10, 戌时(19-21)=11, 亥时(21-23)=12
 *
 * @param year 公历年份
 * @param month 月份（1-12）
 * @param day 日期（1-31）
 * @param hour 小时（0-23）
 * @returns 起卦结果
 */
export function divinationByTime(
  year: number,
  month: number,
  day: number,
  hour: number
): DivinationResult {
  // 获取年支数
  const yearBranch = getYearBranchNumber(year);

  // 获取时辰数（小时转地支序号）
  // 子时(23-01)=1, 丑时(01-03)=2, ..., 亥时(21-23)=12
  const hourBranch = Math.floor(((hour + 1) % 24) / 2) + 1;

  // 计算上卦数字和
  const upperSum = yearBranch + month + day;
  // 计算下卦数字和（包含时辰）
  const lowerSum = upperSum + hourBranch;

  // 上卦：数字和 mod 8
  const upperNumber = calculateMod8(upperSum);
  // 下卦：数字和（含时辰）mod 8
  const lowerNumber = calculateMod8(lowerSum);
  // 动爻：总和 mod 6
  const movingLine = calculateMod6(lowerSum);

  // 生成主卦
  const mainGua = generateGuaXiang(upperNumber, lowerNumber, movingLine);

  // 确定体用卦
  const { bodyGua, useGua, bodyTrigram, useTrigram } = determineBodyUse(mainGua, movingLine);

  // 计算互卦
  const mutualGua = calculateMutualGua(mainGua);

  // 计算变卦
  const changedGua = calculateChangedGua(mainGua, movingLine);

  return {
    method: '时间起卦',
    methodEN: 'Time',
    timestamp: new Date(year, month - 1, day, hour),
    input: { year, month, day, hour, yearBranch, hourBranch },
    mainGua,
    mutualGua,
    changedGua,
    movingLine,
    bodyGua,
    useGua,
    bodyTrigram,
    useTrigram,
  };
}

/**
 * 数字起卦法
 * Number-based divination method
 *
 * 算法说明 / Algorithm description:
 * - 取第一个数 mod 8 为上卦
 * - 取第二个数 mod 8 为下卦
 * - 两数之和 mod 6 为动爻
 * - 如果只有一个数，则该数 mod 8 为上卦，该数 mod 8 为下卦（取余后加1作为下卦）
 *
 * Upper trigram: N_1 mod 8
 * Lower trigram: N_2 mod 8
 * Moving line:   (N_1 + N_2) mod 6
 *
 * @param num1 第一个数字
 * @param num2 第二个数字（可选，缺省等于 num1）
 * @returns 起卦结果
 */
export function divinationByNumber(num1: number, num2?: number): DivinationResult {
  const n1 = Math.abs(Math.floor(num1));
  const n2 = num2 !== undefined ? Math.abs(Math.floor(num2)) : n1;

  const upperNumber = calculateMod8(n1);
  const lowerNumber = calculateMod8(n2);
  const movingLine = calculateMod6(n1 + n2);

  const mainGua = generateGuaXiang(upperNumber, lowerNumber, movingLine);
  const { bodyGua, useGua, bodyTrigram, useTrigram } = determineBodyUse(mainGua, movingLine);
  const mutualGua = calculateMutualGua(mainGua);
  const changedGua = calculateChangedGua(mainGua, movingLine);

  return {
    method: '数字起卦',
    methodEN: 'Number',
    timestamp: new Date(),
    input: { num1: n1, num2: n2 },
    mainGua,
    mutualGua,
    changedGua,
    movingLine,
    bodyGua,
    useGua,
    bodyTrigram,
    useTrigram,
  };
}

/**
 * 文字起卦法（笔画起卦法）
 * Text-based divination method (stroke count method)
 *
 * 算法说明 / Algorithm description:
 * - 单字：总笔画 mod 8 为上卦，总笔画 mod 8 为下卦，总笔画 mod 6 为动爻
 * - 双字：第一字笔画 mod 8 为上卦，第二字笔画 mod 8 为下卦，总笔画 mod 6 为动爻
 * - 多字：前半笔画之和 mod 8 为上卦，后半笔画之和 mod 8 为下卦，总笔画 mod 6 为动爻
 *
 * 注意：此函数接受笔画数数组，笔画数的获取需要调用方提供。
 * Note: This function accepts stroke count arrays. Getting actual stroke counts
 * requires an external Chinese character stroke dictionary.
 *
 * @param strokeCounts 文字笔画数数组
 * @param text 原始文字（仅用于记录）
 * @returns 起卦结果
 */
export function divinationByText(strokeCounts: number[], text?: string): DivinationResult {
  if (strokeCounts.length === 0) {
    throw new Error('文字起卦需要至少一个字的笔画数 / Text divination requires at least one stroke count');
  }

  let upperSum: number;
  let lowerSum: number;
  let totalSum: number;

  if (strokeCounts.length === 1) {
    // 单字：笔画数同时用于上下卦
    upperSum = strokeCounts[0];
    lowerSum = strokeCounts[0];
    totalSum = strokeCounts[0];
  } else if (strokeCounts.length === 2) {
    // 双字：第一字为上卦，第二字为下卦
    upperSum = strokeCounts[0];
    lowerSum = strokeCounts[1];
    totalSum = strokeCounts[0] + strokeCounts[1];
  } else {
    // 多字：前半为上卦，后半为下卦
    const mid = Math.ceil(strokeCounts.length / 2);
    upperSum = strokeCounts.slice(0, mid).reduce((a, b) => a + b, 0);
    lowerSum = strokeCounts.slice(mid).reduce((a, b) => a + b, 0);
    totalSum = strokeCounts.reduce((a, b) => a + b, 0);
  }

  const upperNumber = calculateMod8(upperSum);
  const lowerNumber = calculateMod8(lowerSum);
  const movingLine = calculateMod6(totalSum);

  const mainGua = generateGuaXiang(upperNumber, lowerNumber, movingLine);
  const { bodyGua, useGua, bodyTrigram, useTrigram } = determineBodyUse(mainGua, movingLine);
  const mutualGua = calculateMutualGua(mainGua);
  const changedGua = calculateChangedGua(mainGua, movingLine);

  return {
    method: '文字起卦',
    methodEN: 'Text',
    timestamp: new Date(),
    input: { text: text || '', strokeCounts },
    mainGua,
    mutualGua,
    changedGua,
    movingLine,
    bodyGua,
    useGua,
    bodyTrigram,
    useTrigram,
  };
}

/**
 * 随机起卦法
 * Random divination method
 *
 * 算法说明 / Algorithm description:
 * 生成三个 1-8 之间的随机数，分别作为上卦、下卦和动爻。
 * Generate three random numbers 1-8 for upper trigram, lower trigram, and moving line.
 *
 * @returns 起卦结果
 */
export function divinationByRandom(): DivinationResult {
  const upperNumber = generateRandomNumber(1, 8);
  const lowerNumber = generateRandomNumber(1, 8);
  const movingLine = generateRandomNumber(1, 6);

  const mainGua = generateGuaXiang(upperNumber, lowerNumber, movingLine);
  const { bodyGua, useGua, bodyTrigram, useTrigram } = determineBodyUse(mainGua, movingLine);
  const mutualGua = calculateMutualGua(mainGua);
  const changedGua = calculateChangedGua(mainGua, movingLine);

  return {
    method: '随机起卦',
    methodEN: 'Random',
    timestamp: new Date(),
    input: null,
    mainGua,
    mutualGua,
    changedGua,
    movingLine,
    bodyGua,
    useGua,
    bodyTrigram,
    useTrigram,
  };
}

// ==================== 体用关系 Body-Use Relationship ====================

/**
 * 确定体卦和用卦
 * Determine body (ti) and use (yong) hexagrams
 *
 * 规则 / Rules:
 * - 动爻在下卦（1-3爻）：下卦为用卦，上卦为体卦
 * - 动爻在上卦（4-6爻）：上卦为用卦，下卦为体卦
 *
 * If moving line is in lower trigram (lines 1-3):
 *   lower trigram = use, upper trigram = body
 * If moving line is in upper trigram (lines 4-6):
 *   upper trigram = use, lower trigram = body
 *
 * @param mainGua 主卦
 * @param movingLine 动爻位置（1-6）
 * @returns 体用卦信息
 */
export function determineBodyUse(
  mainGua: GuaXiang,
  movingLine: number
): {
  bodyGua: GuaXiang;
  useGua: GuaXiang;
  bodyTrigram: BaGua;
  useTrigram: BaGua;
} {
  const isMovingInLower = movingLine <= 3;

  // 体卦：不动的经卦  Body: the trigram without the moving line
  // 用卦：有动爻的经卦  Use: the trigram with the moving line
  const bodyTrigram = isMovingInLower ? mainGua.upperTrigram : mainGua.lowerTrigram;
  const useTrigram = isMovingInLower ? mainGua.lowerTrigram : mainGua.upperTrigram;

  // 体用卦本质上与主卦相同，只是关注点不同
  const bodyGua = { ...mainGua };
  const useGua = { ...mainGua };

  return {
    bodyGua,
    useGua,
    bodyTrigram,
    useTrigram,
  };
}

// ==================== 互卦与变卦 Mutual and Changed Hexagrams ====================

/**
 * 计算互卦
 * Calculate mutual hexagram (hu gua)
 *
 * 互卦算法 / Mutual hexagram algorithm:
 * 取主卦的第2、3、4爻为互卦的下卦
 * 取主卦的第3、4、5爻为互卦的上卦
 *
 * Lower trigram of mutual: lines 2, 3, 4 of main hexagram
 * Upper trigram of mutual: lines 3, 4, 5 of main hexagram
 *
 * @param mainGua 主卦
 * @returns 互卦
 */
export function calculateMutualGua(mainGua: GuaXiang): GuaXiang {
  const lines = mainGua.lines;

  // 互卦下卦：取主卦第2、3、4爻
  // Mutual lower trigram: lines 2, 3, 4
  const mutualLower: YaoLine[] = [lines[1].line, lines[2].line, lines[3].line];

  // 互卦上卦：取主卦第3、4、5爻
  // Mutual upper trigram: lines 3, 4, 5
  const mutualUpper: YaoLine[] = [lines[2].line, lines[3].line, lines[4].line];

  // 根据爻线反推八卦数字
  const lowerNumber = trigramLinesToNumber(mutualLower);
  const upperNumber = trigramLinesToNumber(mutualUpper);

  // 互卦没有动爻，动爻位置设为0
  return generateGuaXiang(upperNumber, lowerNumber, 0);
}

/**
 * 计算变卦
 * Calculate changed hexagram (bian gua)
 *
 * 变卦算法 / Changed hexagram algorithm:
 * 将主卦的动爻阴阳互变（阳变阴，阴变阳），其余爻不变。
 *
 * Flip the moving line (Yang<->Yin), keep other lines unchanged.
 *
 * @param mainGua 主卦
 * @param movingLine 动爻位置（1-6）
 * @returns 变卦
 */
export function calculateChangedGua(mainGua: GuaXiang, movingLine: number): GuaXiang {
  const lines = mainGua.lines.map((yao, index) => {
    if (index + 1 === movingLine) {
      // 动爻变：阳变阴，阴变阳
      // Flip moving line: Yang->Yin, Yin->Yang
      return {
        ...yao,
        line: yao.line === '阳' ? '阴' as YaoLine : '阳' as YaoLine,
        lineEN: yao.line === '阳' ? 'Yin' as YaoLineEN : 'Yang' as YaoLineEN,
        isMoving: true,
      };
    }
    return { ...yao, isMoving: false };
  });

  // 从变爻后的新线路反推上下卦数字
  const changedLower: YaoLine[] = [lines[0].line, lines[1].line, lines[2].line];
  const changedUpper: YaoLine[] = [lines[3].line, lines[4].line, lines[5].line];

  const lowerNumber = trigramLinesToNumber(changedLower);
  const upperNumber = trigramLinesToNumber(changedUpper);

  const changed = generateGuaXiang(upperNumber, lowerNumber, 0);
  // 保留原始的变爻信息
  changed.lines = lines;

  return changed;
}

/**
 * 根据三爻线反推八卦数字
 * Infer trigram number from three Yao lines
 *
 * @param lines 三爻数组（从下到上）
 * @returns 1-8 的八卦数字
 */
export function trigramLinesToNumber(lines: YaoLine[]): number {
  // 先天八卦二进制到数字映射（从下到上）
  const binaryToNumber: Record<string, number> = {
    '111': 1,  // 乾
    '110': 2,  // 兑
    '101': 3,  // 离
    '100': 4,  // 震
    '011': 5,  // 巽
    '010': 6,  // 坎
    '001': 7,  // 艮
    '000': 8,  // 坤
  };

  const binary = lines.map(l => l === '阳' ? '1' : '0').join('');
  return binaryToNumber[binary] || 1;
}

// ==================== 五行分析 Five-Element Analysis ====================

/**
 * 分析体用五行关系
 * Analyze body-use five-element relationship
 *
 * 梅花易数以体卦为主（求测者/事物），用卦为客（外部环境/变化因素）。
 * 通过五行生克判断事情的吉凶趋势。
 *
 * In Plum Blossom numerology, the body hexagram represents the querent,
 * and the use hexagram represents external factors.
 * Five-element relationships determine fortune trends.
 *
 * @param bodyTrigram 体卦的经卦
 * @param useTrigram 用卦的经卦
 * @param month 当前月份（1-12，用于判断卦气旺衰）
 * @returns 五行分析结果
 */
export function analyzeWuXing(
  bodyTrigram: BaGua,
  useTrigram: BaGua,
  month: number
): WuXingAnalysis {
  const bodyElement = BAGUA_WUXING_MAP[bodyTrigram];
  const useElement = BAGUA_WUXING_MAP[useTrigram];
  const bodyElementEN = BAGUA_WUXING_MAP_EN[getBaGuaByNumberEN(
    Object.entries(BAGUA_NUMBER_MAP).find(([, v]) => v === bodyTrigram)?.[0]
      ? Number(Object.entries(BAGUA_NUMBER_MAP).find(([, v]) => v === bodyTrigram)![0])
      : 1
  )] || 'Metal';
  const useElementEN = BAGUA_WUXING_MAP_EN[getBaGuaByNumberEN(
    Object.entries(BAGUA_NUMBER_MAP).find(([, v]) => v === useTrigram)?.[0]
      ? Number(Object.entries(BAGUA_NUMBER_MAP).find(([, v]) => v === useTrigram)![0])
      : 1
  )] || 'Metal';

  // 获取五行关系
  const relationKey = WUXING_RELATION_MATRIX[bodyElement][useElement];
  let relation: WuXingAnalysis['relation'];
  let relationEN: WuXingAnalysis['relationEN'];

  switch (relationKey) {
    case '生':
      relation = '生';
      relationEN = 'generates';
      break;
    case '克':
      relation = '克';
      relationEN = 'destroys';
      break;
    case '被生':
      relation = '被生';
      relationEN = 'generated by';
      break;
    case '被克':
      relation = '被克';
      relationEN = 'destroyed by';
      break;
    default:
      relation = '同';
      relationEN = 'same';
  }

  // 获取季节旺衰
  const season = getSeasonByMonth(month);
  const bodyState = getElementSeasonalState(bodyElement, season);
  const bodyStateEN = getElementSeasonalStateEN(bodyElement, season);
  const useState = getElementSeasonalState(useElement, season);
  const useStateEN = getElementSeasonalStateEN(useElement, season);

  // 生成解读
  const interpretation = generateWuXingInterpretation(
    bodyElement, useElement, relation, bodyState, useState
  );
  const interpretationEN = generateWuXingInterpretationEN(
    bodyElementEN, useElementEN, relationEN, bodyStateEN, useStateEN
  );

  return {
    bodyElement,
    bodyElementEN,
    useElement,
    useElementEN,
    relation,
    relationEN,
    bodySeasonalState: bodyState,
    bodySeasonalStateEN: bodyStateEN,
    useSeasonalState: useState,
    useSeasonalStateEN: useStateEN,
    interpretation,
    interpretationEN,
  };
}

/**
 * 生成五行关系解读（中文）
 * Generate five-element interpretation (Chinese)
 */
function generateWuXingInterpretation(
  bodyElement: WuXingElement,
  useElement: WuXingElement,
  relation: WuXingAnalysis['relation'],
  bodyState: WuXingAnalysis['bodySeasonalState'],
  useState: WuXingAnalysis['useSeasonalState']
): string {
  const stateMeaning: Record<string, string> = {
    '旺': '得势，力量强盛',
    '相': '得助，力量适中',
    '休': '休息，力量减弱',
    '囚': '受制，力量受阻',
    '死': '衰弱，力量不足',
  };

  let relationMeaning: string;
  switch (relation) {
    case '生':
      relationMeaning = `体卦${bodyElement}生用卦${useElement}，体卦泄气给用卦，主耗泄、付出`;
      break;
    case '克':
      relationMeaning = `体卦${bodyElement}克用卦${useElement}，体卦制御用卦，主控制、主动`;
      break;
    case '被生':
      relationMeaning = `用卦${useElement}生体卦${bodyElement}，用卦滋养体卦，主得助、受益`;
      break;
    case '被克':
      relationMeaning = `用卦${useElement}克体卦${bodyElement}，用卦压制体卦，主受制、阻碍`;
      break;
    case '同':
      relationMeaning = `体卦与用卦同属${bodyElement}，比和之象，主平稳、和谐`;
      break;
  }

  return `${relationMeaning}。体卦${bodyElement}当令${stateMeaning[bodyState]}，用卦${useElement}当令${stateMeaning[useState]}。`;
}

/**
 * 生成五行关系解读（英文）
 * Generate five-element interpretation (English)
 */
function generateWuXingInterpretationEN(
  bodyElement: WuXingElementEN,
  useElement: WuXingElementEN,
  relation: WuXingAnalysis['relationEN'],
  bodyState: WuXingAnalysis['bodySeasonalStateEN'],
  useState: WuXingAnalysis['useSeasonalStateEN']
): string {
  const stateMeaning: Record<string, string> = {
    'Prosperous': 'in full power, strong vitality',
    'Generating': 'supported, moderate strength',
    'Resting': 'at rest, diminished strength',
    'Imprisoned': 'restricted, blocked energy',
    'Dead': 'weakened, insufficient power',
  };

  let relationMeaning: string;
  switch (relation) {
    case 'generates':
      relationMeaning = `Body (${bodyElement}) generates Use (${useElement}), body exhausts energy to support use — indicates expenditure and effort`;
      break;
    case 'destroys':
      relationMeaning = `Body (${bodyElement}) destroys Use (${useElement}), body controls use — indicates control and initiative`;
      break;
    case 'generated by':
      relationMeaning = `Use (${useElement}) generates Body (${bodyElement}), use nourishes body — indicates receiving help and benefit`;
      break;
    case 'destroyed by':
      relationMeaning = `Use (${useElement}) destroys Body (${bodyElement}), use suppresses body — indicates restriction and obstacles`;
      break;
    case 'same':
      relationMeaning = `Body and Use share ${bodyElement} element, harmony — indicates stability and balance`;
      break;
  }

  return `${relationMeaning}. Body (${bodyElement}) is ${stateMeaning[bodyState]}, Use (${useElement}) is ${stateMeaning[useState]}.`;
}

// ==================== 综合断卦 Comprehensive Interpretation ====================

/**
 * 综合断卦
 * Comprehensive hexagram interpretation
 *
 * 整合主卦、互卦、变卦的五行关系，结合体用关系和卦气旺衰，
 * 给出综合性的判断和建议。
 *
 * Integrates five-element relationships of main, mutual, and changed hexagrams,
 * combined with body-use relationships and seasonal states,
 * to provide comprehensive judgment and advice.
 *
 * @param divinationResult 起卦结果
 * @param month 当前月份（1-12）
 * @returns 综合断卦结果
 */
export function comprehensiveInterpretation(
  divinationResult: DivinationResult,
  month: number
): ComprehensiveInterpretation {
  // 分析主卦体用五行关系
  const wuxingAnalysis = analyzeWuXing(
    divinationResult.bodyTrigram,
    divinationResult.useTrigram,
    month
  );

  // 分析互卦五行关系（互卦显示事情发展的过程）
  const mutualAnalysis = divinationResult.mutualGua
    ? analyzeWuXing(
        divinationResult.mutualGua.lowerTrigram,
        divinationResult.mutualGua.upperTrigram,
        month
      )
    : null;

  // 分析变卦五行关系（变卦显示事情的最终结果）
  const changedAnalysis = divinationResult.changedGua
    ? analyzeWuXing(
        divinationResult.changedGua.lowerTrigram,
        divinationResult.changedGua.upperTrigram,
        month
      )
    : null;

  // 综合判断
  const overallResult = generateOverallInterpretation(
    wuxingAnalysis,
    mutualAnalysis,
    changedAnalysis
  );

  // 生成各方面预测
  const aspects = generateAspectPredictions(wuxingAnalysis, divinationResult);

  return {
    divinationResult,
    wuxingAnalysis,
    overallInterpretation: overallResult.chinese,
    overallInterpretationEN: overallResult.english,
    advice: overallResult.advice,
    adviceEN: overallResult.adviceEN,
    confidence: overallResult.confidence,
    aspects,
  };
}

/**
 * 生成综合解读
 * Generate overall interpretation
 */
function generateOverallInterpretation(
  mainAnalysis: WuXingAnalysis,
  mutualAnalysis: WuXingAnalysis | null,
  changedAnalysis: WuXingAnalysis | null
): {
  chinese: string;
  english: string;
  advice: string;
  adviceEN: string;
  confidence: number;
} {
  // 吉凶判断基础逻辑
  // Auspiciousness determination logic
  let fortune: '吉' | '凶' | '平';
  let fortuneEN: 'Auspicious' | 'Inauspicious' | 'Neutral';

  // 体卦被生最吉，体卦生用泄气次吉，比和为平，体克用小凶，体被克最凶
  // Body generated by use is most auspicious, body generates use is second,
  // same element is neutral, body destroys use is slightly inauspicious,
  // body destroyed by use is most inauspicious
  switch (mainAnalysis.relation) {
    case '被生':
      fortune = '吉';
      fortuneEN = 'Auspicious';
      break;
    case '生':
      fortune = '平';
      fortuneEN = 'Neutral';
      break;
    case '同':
      fortune = '平';
      fortuneEN = 'Neutral';
      break;
    case '克':
      fortune = '平';
      fortuneEN = 'Neutral';
      break;
    case '被克':
      fortune = '凶';
      fortuneEN = 'Inauspicious';
      break;
  }

  // 结合卦气旺衰调整
  // Adjust based on seasonal state
  if (mainAnalysis.bodySeasonalState === '旺' || mainAnalysis.bodySeasonalState === '相') {
    // 体卦得令，加分
    if (fortune === '凶') fortune = '平';
    if (fortune === '平') fortune = '吉';
  } else if (mainAnalysis.bodySeasonalState === '死' || mainAnalysis.bodySeasonalState === '囚') {
    // 体卦失令，减分
    if (fortune === '吉') fortune = '平';
    if (fortune === '平') fortune = '凶';
  }

  // 构建解读文本
  const fortuneText = fortune === '吉' ? '吉利' : fortune === '凶' ? '不利' : '平稳';
  const fortuneTextEN = fortuneEN;

  let chinese = `【综合断卦】${fortuneText}。${mainAnalysis.interpretation}`;
  let english = `[Overall] ${fortuneTextEN}. ${mainAnalysis.interpretationEN}`;

  // 如果有互卦分析，添加过程描述
  if (mutualAnalysis) {
    chinese += `事情发展过程中，${mutualAnalysis.interpretation}`;
    english += ` During development, ${mutualAnalysis.interpretationEN}`;
  }

  // 如果有变卦分析，添加结果描述
  if (changedAnalysis) {
    chinese += `最终结果趋向：${changedAnalysis.interpretation}`;
    english += ` Final outcome tends toward: ${changedAnalysis.interpretationEN}`;
  }

  // 生成建议
  let advice: string;
  let adviceEN: string;

  switch (fortune) {
    case '吉':
      advice = '此卦吉利，宜积极进取，把握时机。体卦得势，做事容易成功，但也要注意不要过于冒进。';
      adviceEN = 'This hexagram is auspicious. Take initiative and seize opportunities. The body hexagram is strong, making success likely, but avoid being overly aggressive.';
      break;
    case '凶':
      advice = '此卦不利，宜谨慎守成，静观其变。体卦受制，做事容易遇到阻碍，建议等待时机或调整策略。';
      adviceEN = 'This hexagram is inauspicious. Be cautious and observe changes. The body hexagram is suppressed, indicating obstacles. Consider waiting for better timing or adjusting strategy.';
      break;
    default:
      advice = '此卦平稳，宜稳中求进。没有明显的吉凶倾向，按部就班，循序渐进即可。';
      adviceEN = 'This hexagram is neutral. Progress steadily. There is no clear auspicious or inauspicious tendency — proceed step by step.';
  }

  // 计算置信度
  // Confidence based on body state strength
  let confidence = 60; // 基础置信度
  if (mainAnalysis.bodySeasonalState === '旺') confidence += 20;
  else if (mainAnalysis.bodySeasonalState === '相') confidence += 10;
  else if (mainAnalysis.bodySeasonalState === '死') confidence -= 10;
  else if (mainAnalysis.bodySeasonalState === '囚') confidence -= 5;

  // 如果互卦和变卦分析一致，增加置信度
  if (mutualAnalysis && changedAnalysis) {
    if (mutualAnalysis.relation === mainAnalysis.relation &&
        changedAnalysis.relation === mainAnalysis.relation) {
      confidence += 10;
    }
  }

  confidence = Math.max(30, Math.min(95, confidence));

  return {
    chinese,
    english,
    advice,
    adviceEN,
    confidence,
  };
}

/**
 * 生成各方面预测
 * Generate predictions for various aspects
 */
function generateAspectPredictions(
  wuxingAnalysis: WuXingAnalysis,
  divinationResult: DivinationResult
): ComprehensiveInterpretation['aspects'] {
  const { relation, bodyElement, useElement, bodySeasonalState } = wuxingAnalysis;
  const { bodyTrigram } = divinationResult;

  // 根据八卦象征和五行关系推断各方面运势
  // Infer fortune for various aspects based on trigram symbols and five-element relationships

  const aspects: ComprehensiveInterpretation['aspects'] = {};

  // 事业运（与体用关系和上卦象征相关）
  // Career fortune (related to body-use relationship and upper trigram symbols)
  aspects.career = generateCareerPrediction(relation, bodySeasonalState, bodyTrigram);
  aspects.careerEN = generateCareerPredictionEN(relation, bodySeasonalState, bodyTrigram);

  // 感情运（与下卦象征相关）
  // Love fortune (related to lower trigram symbols)
  aspects.love = generateLovePrediction(relation, bodySeasonalState, lowerTrigramFromResult(divinationResult));
  aspects.loveEN = generateLovePredictionEN(relation, bodySeasonalState, lowerTrigramFromResult(divinationResult));

  // 财运（与五行生克关系相关）
  // Wealth fortune (related to five-element relationships)
  aspects.wealth = generateWealthPrediction(relation, bodyElement, useElement);
  aspects.wealthEN = generateWealthPredictionEN(relation, bodyElement, useElement);

  // 健康运（与体卦五行和旺衰相关）
  // Health fortune (related to body element and seasonal state)
  aspects.health = generateHealthPrediction(bodyElement, bodySeasonalState);
  aspects.healthEN = generateHealthPredictionEN(bodyElement, bodySeasonalState);

  return aspects;
}

/**
 * 从起卦结果中获取下卦
 * Get lower trigram from divination result
 */
function lowerTrigramFromResult(result: DivinationResult): BaGua {
  return result.mainGua.lowerTrigram;
}

/**
 * 事业运预测（中文）
 * Career prediction (Chinese)
 */
function generateCareerPrediction(
  relation: WuXingAnalysis['relation'],
  bodyState: WuXingAnalysis['bodySeasonalState'],
  _trigram: BaGua
): string {
  let base: string;
  switch (relation) {
    case '被生': base = '事业发展顺利，有贵人相助'; break;
    case '生': base = '事业需要付出较多努力，有耗泄之象'; break;
    case '克': base = '事业上有一定控制力，但需注意人际关系'; break;
    case '被克': base = '事业受阻，需要调整方向或等待时机'; break;
    case '同': base = '事业平稳，适合维持现状'; break;
  }

  const stateModifier = bodyState === '旺' || bodyState === '相'
    ? '当前运势较旺，是发展的好时机。'
    : '当前运势偏弱，宜守不宜攻。';

  return base + stateModifier;
}

/**
 * 事业运预测（英文）
 * Career prediction (English)
 */
function generateCareerPredictionEN(
  relation: WuXingAnalysis['relation'],
  bodyState: WuXingAnalysis['bodySeasonalState'],
  _trigram: BaGua
): string {
  let base: string;
  switch (relation) {
    case '被生': base = 'Career development is smooth with helpful support. '; break;
    case '生': base = 'Career requires significant effort with signs of energy expenditure. '; break;
    case '克': base = 'You have control in career matters, but watch interpersonal relationships. '; break;
    case '被克': base = 'Career obstacles present; consider adjusting direction or waiting. '; break;
    case '同': base = 'Career is stable; suitable for maintaining the status quo. '; break;
  }

  const stateModifier = bodyState === '旺' || bodyState === '相'
    ? 'Current fortune is strong — good timing for development.'
    : 'Current fortune is weak — better to conserve than advance.';

  return base + stateModifier;
}

/**
 * 感情运预测（中文）
 * Love prediction (Chinese)
 */
function generateLovePrediction(
  relation: WuXingAnalysis['relation'],
  _bodyState: WuXingAnalysis['bodySeasonalState'],
  _trigram: BaGua
): string {
  switch (relation) {
    case '被生': return '感情运势良好，双方互相滋养，关系和谐融洽。';
    case '生': return '感情中付出较多，需要平衡双方关系，避免过度付出。';
    case '克': return '感情中存在一些摩擦，需要包容理解，控制情绪。';
    case '被克': return '感情遇到阻力，可能出现矛盾或误解，需要冷静处理。';
    case '同': return '感情平稳，双方处于平等状态，适合加深了解。';
  }
}

/**
 * 感情运预测（英文）
 * Love prediction (English)
 */
function generateLovePredictionEN(
  relation: WuXingAnalysis['relation'],
  _bodyState: WuXingAnalysis['bodySeasonalState'],
  _trigram: BaGua
): string {
  switch (relation) {
    case '被生': return 'Love fortune is excellent. Both parties nourish each other, relationship is harmonious.';
    case '生': return 'You are giving more in the relationship. Balance is needed to avoid over-giving.';
    case '克': return 'Some friction exists in the relationship. Practice tolerance and emotional control.';
    case '被克': return 'Love faces resistance. Conflicts or misunderstandings may arise — handle calmly.';
    case '同': return 'Love is stable with both parties on equal footing. Good time to deepen understanding.';
  }
}

/**
 * 财运预测（中文）
 * Wealth prediction (Chinese)
 */
function generateWealthPrediction(
  relation: WuXingAnalysis['relation'],
  bodyElement: WuXingElement,
  useElement: WuXingElement
): string {
  switch (relation) {
    case '被生': return `用卦${useElement}生体卦${bodyElement}，财运亨通，有进财之象，适合投资和理财。`;
    case '生': return `体卦${bodyElement}生用卦${useElement}，财有流出之象，注意节约开支，避免冲动消费。`;
    case '克': return `体卦${bodyElement}克用卦${useElement}，可以主动求财，但不宜过于激进。`;
    case '被克': return `用卦${useElement}克体卦${bodyElement}，财运受阻，不宜大额投资或借贷。`;
    case '同': return `体用同属${bodyElement}，财运平稳，收支平衡，适合稳健理财。`;
  }
}

/**
 * 财运预测（英文）
 * Wealth prediction (English)
 */
function generateWealthPredictionEN(
  relation: WuXingAnalysis['relation'],
  bodyElement: WuXingElement,
  useElement: WuXingElement
): string {
  switch (relation) {
    case '被生': return `Use (${useElement}) generates Body (${bodyElement}). Wealth flows in — good for investments and financial management.`;
    case '生': return `Body (${bodyElement}) generates Use (${useElement}). Wealth flows out — watch expenses and avoid impulse spending.`;
    case '克': return `Body (${bodyElement}) destroys Use (${useElement}). Active pursuit of wealth is possible, but avoid being too aggressive.`;
    case '被克': return `Use (${useElement}) destroys Body (${bodyElement}). Wealth faces obstacles — avoid large investments or loans.`;
    case '同': return `Body and Use share ${bodyElement}. Wealth is stable with balanced income and expenses — suitable for steady financial management.`;
  }
}

/**
 * 健康运预测（中文）
 * Health prediction (Chinese)
 */
function generateHealthPrediction(
  bodyElement: WuXingElement,
  bodyState: WuXingAnalysis['bodySeasonalState']
): string {
  const organMap: Record<WuXingElement, string> = {
    '金': '肺和大肠',
    '木': '肝和胆',
    '水': '肾和膀胱',
    '火': '心和小肠',
    '土': '脾和胃',
  };

  let stateText: string;
  switch (bodyState) {
    case '旺': stateText = '身体状况良好，精力充沛'; break;
    case '相': stateText = '身体状况尚可，注意劳逸结合'; break;
    case '休': stateText = '身体容易疲劳，需要多休息'; break;
    case '囚': stateText = '身体容易不适，注意保养'; break;
    case '死': stateText = '身体较弱，需要特别注意健康'; break;
  }

  return `${stateText}。体卦属${bodyElement}，特别注意${organMap[bodyElement]}的保养。`;
}

/**
 * 健康运预测（英文）
 * Health prediction (English)
 */
function generateHealthPredictionEN(
  bodyElement: WuXingElement,
  bodyState: WuXingAnalysis['bodySeasonalState']
): string {
  const organMap: Record<WuXingElement, string> = {
    '金': 'lungs and large intestine',
    '木': 'liver and gallbladder',
    '水': 'kidneys and bladder',
    '火': 'heart and small intestine',
    '土': 'spleen and stomach',
  };

  let stateText: string;
  switch (bodyState) {
    case '旺': stateText = 'Health is good with abundant energy. '; break;
    case '相': stateText = 'Health is fair — balance work and rest. '; break;
    case '休': stateText = 'Body is prone to fatigue — more rest needed. '; break;
    case '囚': stateText = 'Body may feel unwell — pay attention to maintenance. '; break;
    case '死': stateText = 'Body is weak — extra health caution needed. '; break;
  }

  return `${stateText}Body element is ${bodyElement} — pay special attention to the ${organMap[bodyElement]}.`;
}

// ==================== 便捷入口函数 Convenience Entry Functions ====================

/**
 * 快速起卦（当前时间）
 * Quick divination using current time
 * @returns 起卦结果
 */
export function quickDivination(): DivinationResult {
  const now = new Date();
  return divinationByTime(
    now.getFullYear(),
    now.getMonth() + 1,
    now.getDate(),
    now.getHours()
  );
}

/**
 * 快速断卦（当前时间）
 * Quick interpretation using current time
 * @returns 综合断卦结果
 */
export function quickInterpretation(): ComprehensiveInterpretation {
  const now = new Date();
  const result = divinationByTime(
    now.getFullYear(),
    now.getMonth() + 1,
    now.getDate(),
    now.getHours()
  );
  return comprehensiveInterpretation(result, now.getMonth() + 1);
}